package ru.agent.beldum.sandbox.sandbox;

/*Generated by MPS */


public class Order {
  private String ourName;
  private long ourAmount;
  private byte ourSecurityCode;

  public Order() {
  }

  public String getName() {
    return Order.this.ourName;
  }

  public void setName(String value) {
    Order.this.ourName = value;
  }

  public long getAmount() {
    return Order.this.ourAmount;
  }

  public void setAmount(long value) {
    Order.this.ourAmount = value;
  }

  public byte getSecurityCode() {
    return Order.this.ourSecurityCode;
  }

  public void setSecurityCode(byte value) {
    Order.this.ourSecurityCode = value;
  }
}
