package ru.agent.beldum.sandbox.sandbox;

/*Generated by MPS */

import ru.agent.dictionary.beans.City;

public class TransportOrder {
  private String ourName;
  private long ourAmount;
  private long ourSecurityCide;
  private City ourFromCity;

  public TransportOrder() {
  }

  public String getName() {
    return TransportOrder.this.ourName;
  }

  public void setName(String value) {
    TransportOrder.this.ourName = value;
  }

  public long getAmount() {
    return TransportOrder.this.ourAmount;
  }

  public void setAmount(long value) {
    TransportOrder.this.ourAmount = value;
  }

  public long getSecurityCide() {
    return TransportOrder.this.ourSecurityCide;
  }

  public void setSecurityCide(long value) {
    TransportOrder.this.ourSecurityCide = value;
  }

  public City getFromCity() {
    return TransportOrder.this.ourFromCity;
  }

  public void setFromCity(City value) {
    TransportOrder.this.ourFromCity = value;
  }
}
