package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ClassConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class BeanTransformation_BehaviorDescriptor extends ClassConcept_BehaviorDescriptor implements HasName_BehaviorDescriptor {
  public BeanTransformation_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.BeanTransformation";
  }
}
