package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class BeanField_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setNewChild(thisNode, "propertyImplementation", "jetbrains.mps.baseLanguage.structure.DefaultPropertyImplementation");
    SNode pimpl = SNodeOperations.cast(SLinkOperations.getTarget(thisNode, "propertyImplementation", true), "jetbrains.mps.baseLanguage.structure.DefaultPropertyImplementation");
    SLinkOperations.setNewChild(pimpl, "defaultSetAccessor", "jetbrains.mps.baseLanguage.structure.DefaultSetAccessor");
    SLinkOperations.setNewChild(pimpl, "defaultGetAccessor", "jetbrains.mps.baseLanguage.structure.DefaultGetAccessor");
    SLinkOperations.setNewChild(SLinkOperations.getTarget(pimpl, "defaultSetAccessor", true), "visibility", "jetbrains.mps.baseLanguage.structure.PublicVisibility");
    SPropertyOperations.set(thisNode, "includeInToString", "" + true);
  }

  public static String call_getClearMethodName_1278577714818296598(SNode thisNode) {
    return "clear" + SPropertyOperations.getString(thisNode, "propertyName");
  }
}
