package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class BeanDescriptor_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_getBeanName_3352977046009450890(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, "name");
  }

  public static String call_getBeanFQN_3352977046009450930(SNode thisNode) {
    return SModelOperations.getModelName(SNodeOperations.getModel(thisNode)) + "." + BeanDescriptor_Behavior.call_getBeanName_3352977046009450890(thisNode);
  }
}
