package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Property_BehaviorDescriptor;

public class BeanField_BehaviorDescriptor extends Property_BehaviorDescriptor implements HasDocumentation_BehaviorDescriptor {
  public BeanField_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.BeanField";
  }
}
