package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class BeanFieldReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public BeanFieldReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.BeanFieldReference";
  }
}
