package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ClassConcept_BehaviorDescriptor;

public abstract class BeanDescriptor_BehaviorDescriptor extends ClassConcept_BehaviorDescriptor implements HasDocumentation_BehaviorDescriptor {
  public BeanDescriptor_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.BeanDescriptor";
  }
}
