package ru.agent.beldum.behavior;

/*Generated by MPS */


public class CustomStrategy_BehaviorDescriptor extends TransformationStrategy_BehaviorDescriptor {
  public CustomStrategy_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.CustomStrategy";
  }
}
