package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class DiscardStrategy_BehaviorDescriptor extends TransformationStrategy_BehaviorDescriptor {
  public DiscardStrategy_BehaviorDescriptor() {
  }

  public boolean virtual_supportsTargetField_7599577621034530105(SNode thisNode) {
    return DiscardStrategy_Behavior.virtual_supportsTargetField_7599577621034530105(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.DiscardStrategy";
  }
}
