package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class DiscardStrategy_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_supportsTargetField_7599577621034530105(SNode thisNode) {
    return false;
  }
}
