package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FieldTransformation_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FieldTransformation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.FieldTransformation";
  }
}
