package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface HasName_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
