package ru.agent.beldum.behavior;

/*Generated by MPS */


public class PresentationBean_BehaviorDescriptor extends BeanDescriptor_BehaviorDescriptor {
  public PresentationBean_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.PresentationBean";
  }
}
