package ru.agent.beldum.behavior;

/*Generated by MPS */


public class SimpleCopyStrategy_BehaviorDescriptor extends TransformationStrategy_BehaviorDescriptor {
  public SimpleCopyStrategy_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.SimpleCopyStrategy";
  }
}
