package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class TransformationStrategy_Behavior {
  private static Class[] PARAMETERS_7599577621034530105 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static boolean virtual_supportsTargetField_7599577621034530105(SNode thisNode) {
    return true;
  }

  public static boolean call_supportsTargetField_7599577621034530105(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (Boolean) descriptor.invoke(Boolean.class, SNodeOperations.cast(thisNode, "ru.agent.beldum.structure.TransformationStrategy"), "virtual_supportsTargetField_7599577621034530105", PARAMETERS_7599577621034530105, new Object[]{});
  }

  public static boolean callSuper_supportsTargetField_7599577621034530105(SNode thisNode, String callerConceptFqName) {
    return (Boolean) BehaviorManager.getInstance().invokeSuper(Boolean.class, SNodeOperations.cast(thisNode, "ru.agent.beldum.structure.TransformationStrategy"), callerConceptFqName, "virtual_supportsTargetField_7599577621034530105", PARAMETERS_7599577621034530105, new Object[]{});
  }
}
