package ru.agent.beldum.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public abstract class TransformationStrategy_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TransformationStrategy_BehaviorDescriptor() {
  }

  public boolean virtual_supportsTargetField_7599577621034530105(SNode thisNode) {
    return TransformationStrategy_Behavior.virtual_supportsTargetField_7599577621034530105(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.TransformationStrategy";
  }
}
