package ru.agent.beldum.behavior;

/*Generated by MPS */


public class TransportBean_BehaviorDescriptor extends BeanDescriptor_BehaviorDescriptor {
  public TransportBean_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ru.agent.beldum.structure.TransportBean";
  }
}
