package ru.agent.dictionary.beans;

/*Generated by MPS */


public class City {
  private String ourName;
  private String ourName_en;
  private String ourIata_code;

  public City() {
  }

  public String getName() {
    return City.this.ourName;
  }

  public void setName(String value) {
    City.this.ourName = value;
  }

  public String getName_en() {
    return City.this.ourName_en;
  }

  public void setName_en(String value) {
    City.this.ourName_en = value;
  }

  public String getIata_code() {
    return City.this.ourIata_code;
  }

  public void setIata_code(String value) {
    City.this.ourIata_code = value;
  }
}
