package ru.agent.dictionary.beans;

/*Generated by MPS */


public class Order {
  private String ourName;
  private Order ourUselessSelves;

  public Order() {
  }

  public String getName() {
    return Order.this.ourName;
  }

  public void setName(String value) {
    Order.this.ourName = value;
  }

  public Order getUselessSelves() {
    return Order.this.ourUselessSelves;
  }

  public void setUselessSelves(Order value) {
    Order.this.ourUselessSelves = value;
  }
}
